### ISSUE TITLE
Swag-f2bdiscord Errors

### ISSUE THREAD

**Issue by slimshizn** [linuxserver/docker-mods#483]
```2022-08-28 11:31:55,318 fail2ban.utils          [479]: ERROR   14c49dde8490 -- exec: python3 /config/fail2ban/Fail2Ban.py -a start -j organizr-auth
2022-08-28 11:31:55,319 fail2ban.utils          [479]: ERROR   14c49dde8490 -- stderr: 'Traceback (most recent call last):'
2022-08-28 11:31:55,319 fail2ban.utils          [479]: ERROR   14c49dde8490 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 95, in <module>'
2022-08-28 11:31:55,319 fail2ban.utils          [479]: ERROR   14c49dde8490 -- … 14c49dde8490 -- stderr: '  File "/usr/lib/python3.9/site-packages/geoip2/database.py", line 189, in _get'
2022-08-28 11:31:55,320 fail2ban.utils          [479]: ERROR   14c49dde8490 -- stderr: '    raise geoip2.errors.AddressNotFoundError('
2022-08-28 11:31:55,321 fail2ban.utils          [479]: ERROR   14c49dde8490 -- stderr: 'geoip2.errors.AddressNotFoundError: The address 1.1.1.1 is not in the database.'
2022-08-28 11:31:55,321 fail2ban.utils          [479]: ERROR   14c49dde8490 -- returned 1```

Started having these issues End of July. Maybe coinciding with a swag release?

**Comment by slimshizn** [comment]
Still having the issue.

**Comment by slimshizn** [comment]
?

**Comment by slimshizn** [comment]
Fixed. Had to remove Fail2Ban.py and restart container, then it was happy.
