### ISSUE TITLE
Universal Calibre: pdf output broken

### ISSUE THREAD

**Issue by Arch-Storm** [linuxserver/docker-mods#485]
Hi, the pdf output for ebook-convert is broken. It's missing multiple dependencies, most of which seem to be part of qtwebengine.
After installing qtwebengine through apt in the docker i managed to get it mostly working, but now it throws out an error that chromium cannot be run as root without --no-sandbox.

I guess the pdf output is somehow managed by a chromium instance from qtwebengine which doesn't seem to be included in this mod.

This is the original error, from a fresh install:

```
root@xxx:/books# ebook-convert test.mobi test.pdf
1% Converting input to HTML...
Failed to import PyQt module: PyQt6.QtWebEngineCore with error: libnss3.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "site.py", line 45, in <module>
  File "site.py", line 41, in main
  File "calibre/ebooks/conversion/cli.py", line 419, in main
  File "calibre/ebooks/conversion/plumber.py", line 1106, in run
  File "calibre/ebooks/conversion/plugins/pdf_output.py", line 149, in specialize_options
ImportError: cannot import name 'QWebEnginePage' from 'qt.webengine' (/app/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/webengine.pyc)
```

**Comment by LukeG20** [comment]
@Arch-Storm having the same issue. Could you go into more detail on manually installing QWebEnginePage?

**Comment by paulhybryant** [comment]
Same issue here
