### ISSUE TITLE
Calibre Mod - Fails install when using calibre-web

### ISSUE THREAD

**Issue by delize** [linuxserver/docker-mods#517]
When using the universal calibre mod for calibre-web, the app fails to install resulting in errors.

Host system is Ubuntu 22.04.1/x64

Docker-compose
```
    calibre-web:
        image: ghcr.io/linuxserver/calibre-web
        container_name: calibre-web
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=America/Chicago
            - DOCKER_MODS=ghcr.io/linuxserver/mods:universal-calibre
            - OAUTHLIB_RELAX_TOKEN_SCOPE=1 
        volumes:
            - /mnt/cache/docker/calibre-web:/config:slave
            - '/mnt/mergerfs/ebooks:/pool/all-books:ro'
            - '/mnt/mergerfs/calibre-library:/pool/books:ro'
            - '/mnt/cache/docker/calibre-web/gmail.json:/app/calibre-web/gmail.json'
        # ports:
        #     - 8083:8083
        restart: unless-stopped
```

```
[migrations] no migrations found

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

**** Adding calibre dependencies to package install list ****
[mod-init] **** Installing all mod packages ****
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [114 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/restricted Sources [28.2 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main Sources [1,668 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/universe Sources [22.0 MB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/multiverse Sources [361 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1,792 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/universe Sources [151 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/restricted Sources [25.3 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main Sources [376 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse Sources [12.6 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [16.9 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [938 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [870 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [519 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-security/multiverse Sources [5,116 B]
Get:21 http://archive.ubuntu.com/ubuntu jammy-security/main Sources [147 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-security/universe Sources [78.2 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy-security/restricted Sources [24.6 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [573 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [4,644 B]
Get:26 http://archive.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [474 kB]
Get:27 http://archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [755 kB]
Fetched 49.2 MB in 4s (11.5 MB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libdrm-amdgpu1 libdrm-common libdrm-nouveau2 libdrm-radeon1 libdrm2 libedit2
  libegl-mesa0 libelf1 libgbm1 libgl1 libgl1-mesa-dri libglapi-mesa libglvnd0
  libglx-mesa0 libglx0 libllvm13 libsensors-config libsensors5 libvulkan1
  libwayland-client0 libwayland-server0 libx11-xcb1 libxcb-dri2-0
  libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-shm0 libxcb-sync1
  libxcb-xfixes0 libxfixes3 libxshmfence1 libxxf86vm1 xkb-data
Suggested packages:
  lm-sensors
Recommended packages:
  libgl1-amber-dri mesa-vulkan-drivers | vulkan-icd
The following NEW packages will be installed:
  libdrm-amdgpu1 libdrm-common libdrm-nouveau2 libdrm-radeon1 libdrm2 libedit2
  libegl-mesa0 libegl1 libelf1 libgbm1 libgl1 libgl1-mesa-dri libgl1-mesa-glx
  libglapi-mesa libglvnd0 libglx-mesa0 libglx0 libllvm13 libopengl0
  libsensors-config libsensors5 libvulkan1 libwayland-client0
  libwayland-server0 libx11-xcb1 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0
  libxcb-present0 libxcb-shm0 libxcb-sync1 libxcb-xfixes0 libxdamage1
  libxfixes3 libxkbcommon0 libxshmfence1 libxxf86vm1 xkb-data xz-utils
0 upgraded, 39 newly installed, 0 to remove and 1 not upgraded.
Need to get 31.5 MB of archives.
After this operation, 136 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libelf1 amd64 0.186-1build1 [51.0 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 xkb-data all 2.33-1 [394 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdrm-common all 2.4.110-1ubuntu1 [5,360 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdrm2 amd64 2.4.110-1ubuntu1 [37.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 libedit2 amd64 3.1-20210910-1build1 [96.8 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 xz-utils amd64 5.2.5-2ubuntu1 [84.8 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdrm-amdgpu1 amd64 2.4.110-1ubuntu1 [20.0 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdrm-nouveau2 amd64 2.4.110-1ubuntu1 [17.4 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdrm-radeon1 amd64 2.4.110-1ubuntu1 [21.5 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libwayland-server0 amd64 1.20.0-1ubuntu0.1 [34.3 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgbm1 amd64 22.0.5-0ubuntu0.1 [32.6 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglapi-mesa amd64 22.0.5-0ubuntu0.1 [35.3 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libwayland-client0 amd64 1.20.0-1ubuntu0.1 [25.9 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy/main amd64 libx11-xcb1 amd64 2:1.7.5-1 [7,790 B]
Get:15 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-dri2-0 amd64 1.14-3ubuntu3 [7,206 B]
Get:16 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-dri3-0 amd64 1.14-3ubuntu3 [6,968 B]
Get:17 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-present0 amd64 1.14-3ubuntu3 [5,734 B]
Get:18 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-sync1 amd64 1.14-3ubuntu3 [9,416 B]
Get:19 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-xfixes0 amd64 1.14-3ubuntu3 [9,996 B]
Get:20 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxshmfence1 amd64 1.3-1build4 [5,394 B]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libegl-mesa0 amd64 22.0.5-0ubuntu0.1 [112 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libllvm13 amd64 1:13.0.1-2ubuntu2.1 [22.2 MB]
Get:23 http://archive.ubuntu.com/ubuntu jammy/main amd64 libsensors-config all 1:3.6.0-7ubuntu1 [5,274 B]
Get:24 http://archive.ubuntu.com/ubuntu jammy/main amd64 libsensors5 amd64 1:3.6.0-7ubuntu1 [26.3 kB]
Get:25 http://archive.ubuntu.com/ubuntu jammy/main amd64 libvulkan1 amd64 1.3.204.1-2 [128 kB]
Get:26 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgl1-mesa-dri amd64 22.0.5-0ubuntu0.1 [7,471 kB]
Get:27 http://archive.ubuntu.com/ubuntu jammy/main amd64 libglvnd0 amd64 1.4.0-1 [73.6 kB]
Get:28 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-glx0 amd64 1.14-3ubuntu3 [25.9 kB]
Get:29 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcb-shm0 amd64 1.14-3ubuntu3 [5,780 B]
Get:30 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxfixes3 amd64 1:6.0.0-1 [11.7 kB]
Get:31 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxxf86vm1 amd64 1:1.1.4-1build3 [10.4 kB]
Get:32 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglx-mesa0 amd64 22.0.5-0ubuntu0.1 [156 kB]
Get:33 http://archive.ubuntu.com/ubuntu jammy/main amd64 libglx0 amd64 1.4.0-1 [41.0 kB]
Get:34 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgl1 amd64 1.4.0-1 [110 kB]
Get:35 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 libgl1-mesa-glx amd64 22.0.5-0ubuntu0.1 [5,456 B]
Get:36 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxdamage1 amd64 1:1.1.5-2build2 [7,154 B]
Get:37 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxkbcommon0 amd64 1.4.0-1 [125 kB]
Get:38 http://archive.ubuntu.com/ubuntu jammy/main amd64 libegl1 amd64 1.4.0-1 [28.6 kB]
Get:39 http://archive.ubuntu.com/ubuntu jammy/main amd64 libopengl0 amd64 1.4.0-1 [36.5 kB]
Fetched 31.5 MB in 2s (19.5 MB/s)
Selecting previously unselected package libelf1:amd64.
(Reading database ... 11090 files and directories currently installed.)
Preparing to unpack .../00-libelf1_0.186-1build1_amd64.deb ...
Unpacking libelf1:amd64 (0.186-1build1) ...
Selecting previously unselected package xkb-data.
Preparing to unpack .../01-xkb-data_2.33-1_all.deb ...
Unpacking xkb-data (2.33-1) ...
Selecting previously unselected package libdrm-common.
Preparing to unpack .../02-libdrm-common_2.4.110-1ubuntu1_all.deb ...
Unpacking libdrm-common (2.4.110-1ubuntu1) ...
Selecting previously unselected package libdrm2:amd64.
Preparing to unpack .../03-libdrm2_2.4.110-1ubuntu1_amd64.deb ...
Unpacking libdrm2:amd64 (2.4.110-1ubuntu1) ...
Selecting previously unselected package libedit2:amd64.
Preparing to unpack .../04-libedit2_3.1-20210910-1build1_amd64.deb ...
Unpacking libedit2:amd64 (3.1-20210910-1build1) ...
Selecting previously unselected package xz-utils.
Preparing to unpack .../05-xz-utils_5.2.5-2ubuntu1_amd64.deb ...
Unpacking xz-utils (5.2.5-2ubuntu1) ...
Selecting previously unselected package libdrm-amdgpu1:amd64.
Preparing to unpack .../06-libdrm-amdgpu1_2.4.110-1ubuntu1_amd64.deb ...
Unpacking libdrm-amdgpu1:amd64 (2.4.110-1ubuntu1) ...
Selecting previously unselected package libdrm-nouveau2:amd64.
Preparing to unpack .../07-libdrm-nouveau2_2.4.110-1ubuntu1_amd64.deb ...
Unpacking libdrm-nouveau2:amd64 (2.4.110-1ubuntu1) ...
Selecting previously unselected package libdrm-radeon1:amd64.
Preparing to unpack .../08-libdrm-radeon1_2.4.110-1ubuntu1_amd64.deb ...
Unpacking libdrm-radeon1:amd64 (2.4.110-1ubuntu1) ...
Selecting previously unselected package libwayland-server0:amd64.
Preparing to unpack .../09-libwayland-server0_1.20.0-1ubuntu0.1_amd64.deb ...
Unpacking libwayland-server0:amd64 (1.20.0-1ubuntu0.1) ...
Selecting previously unselected package libgbm1:amd64.
Preparing to unpack .../10-libgbm1_22.0.5-0ubuntu0.1_amd64.deb ...
Unpacking libgbm1:amd64 (22.0.5-0ubuntu0.1) ...
Selecting previously unselected package libglapi-mesa:amd64.
Preparing to unpack .../11-libglapi-mesa_22.0.5-0ubuntu0.1_amd64.deb ...
Unpacking libglapi-mesa:amd64 (22.0.5-0ubuntu0.1) ...
Selecting previously unselected package libwayland-client0:amd64.
Preparing to unpack .../12-libwayland-client0_1.20.0-1ubuntu0.1_amd64.deb ...
Unpacking libwayland-client0:amd64 (1.20.0-1ubuntu0.1) ...
Selecting previously unselected package libx11-xcb1:amd64.
Preparing to unpack .../13-libx11-xcb1_2%3a1.7.5-1_amd64.deb ...
Unpacking libx11-xcb1:amd64 (2:1.7.5-1) ...
Selecting previously unselected package libxcb-dri2-0:amd64.
Preparing to unpack .../14-libxcb-dri2-0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-dri2-0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-dri3-0:amd64.
Preparing to unpack .../15-libxcb-dri3-0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-dri3-0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-present0:amd64.
Preparing to unpack .../16-libxcb-present0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-present0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-sync1:amd64.
Preparing to unpack .../17-libxcb-sync1_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-sync1:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-xfixes0:amd64.
Preparing to unpack .../18-libxcb-xfixes0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-xfixes0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxshmfence1:amd64.
Preparing to unpack .../19-libxshmfence1_1.3-1build4_amd64.deb ...
Unpacking libxshmfence1:amd64 (1.3-1build4) ...
Selecting previously unselected package libegl-mesa0:amd64.
Preparing to unpack .../20-libegl-mesa0_22.0.5-0ubuntu0.1_amd64.deb ...
Unpacking libegl-mesa0:amd64 (22.0.5-0ubuntu0.1) ...
Selecting previously unselected package libllvm13:amd64.
Preparing to unpack .../21-libllvm13_1%3a13.0.1-2ubuntu2.1_amd64.deb ...
Unpacking libllvm13:amd64 (1:13.0.1-2ubuntu2.1) ...
Selecting previously unselected package libsensors-config.
Preparing to unpack .../22-libsensors-config_1%3a3.6.0-7ubuntu1_all.deb ...
Unpacking libsensors-config (1:3.6.0-7ubuntu1) ...
Selecting previously unselected package libsensors5:amd64.
Preparing to unpack .../23-libsensors5_1%3a3.6.0-7ubuntu1_amd64.deb ...
Unpacking libsensors5:amd64 (1:3.6.0-7ubuntu1) ...
Selecting previously unselected package libvulkan1:amd64.
Preparing to unpack .../24-libvulkan1_1.3.204.1-2_amd64.deb ...
Unpacking libvulkan1:amd64 (1.3.204.1-2) ...
Selecting previously unselected package libgl1-mesa-dri:amd64.
Preparing to unpack .../25-libgl1-mesa-dri_22.0.5-0ubuntu0.1_amd64.deb ...
Unpacking libgl1-mesa-dri:amd64 (22.0.5-0ubuntu0.1) ...
Selecting previously unselected package libglvnd0:amd64.
Preparing to unpack .../26-libglvnd0_1.4.0-1_amd64.deb ...
Unpacking libglvnd0:amd64 (1.4.0-1) ...
Selecting previously unselected package libxcb-glx0:amd64.
Preparing to unpack .../27-libxcb-glx0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-glx0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxcb-shm0:amd64.
Preparing to unpack .../28-libxcb-shm0_1.14-3ubuntu3_amd64.deb ...
Unpacking libxcb-shm0:amd64 (1.14-3ubuntu3) ...
Selecting previously unselected package libxfixes3:amd64.
Preparing to unpack .../29-libxfixes3_1%3a6.0.0-1_amd64.deb ...
Unpacking libxfixes3:amd64 (1:6.0.0-1) ...
Selecting previously unselected package libxxf86vm1:amd64.
Preparing to unpack .../30-libxxf86vm1_1%3a1.1.4-1build3_amd64.deb ...
Unpacking libxxf86vm1:amd64 (1:1.1.4-1build3) ...
Selecting previously unselected package libglx-mesa0:amd64.
Preparing to unpack .../31-libglx-mesa0_22.0.5-0ubuntu0.1_amd64.deb ...
Unpacking libglx-mesa0:amd64 (22.0.5-0ubuntu0.1) ...
Selecting previously unselected package libglx0:amd64.
Preparing to unpack .../32-libglx0_1.4.0-1_amd64.deb ...
Unpacking libglx0:amd64 (1.4.0-1) ...
Selecting previously unselected package libgl1:amd64.
Preparing to unpack .../33-libgl1_1.4.0-1_amd64.deb ...
Unpacking libgl1:amd64 (1.4.0-1) ...
Selecting previously unselected package libgl1-mesa-glx:amd64.
Preparing to unpack .../34-libgl1-mesa-glx_22.0.5-0ubuntu0.1_amd64.deb ...
Unpacking libgl1-mesa-glx:amd64 (22.0.5-0ubuntu0.1) ...
Selecting previously unselected package libxdamage1:amd64.
Preparing to unpack .../35-libxdamage1_1%3a1.1.5-2build2_amd64.deb ...
Unpacking libxdamage1:amd64 (1:1.1.5-2build2) ...
Selecting previously unselected package libxkbcommon0:amd64.
Preparing to unpack .../36-libxkbcommon0_1.4.0-1_amd64.deb ...
Unpacking libxkbcommon0:amd64 (1.4.0-1) ...
Selecting previously unselected package libegl1:amd64.
Preparing to unpack .../37-libegl1_1.4.0-1_amd64.deb ...
Unpacking libegl1:amd64 (1.4.0-1) ...
Selecting previously unselected package libopengl0:amd64.
Preparing to unpack .../38-libopengl0_1.4.0-1_amd64.deb ...
Unpacking libopengl0:amd64 (1.4.0-1) ...
Setting up libxcb-dri3-0:amd64 (1.14-3ubuntu3) ...
Setting up libwayland-server0:amd64 (1.20.0-1ubuntu0.1) ...
Setting up libx11-xcb1:amd64 (2:1.7.5-1) ...
Setting up libxdamage1:amd64 (1:1.1.5-2build2) ...
Setting up libxcb-xfixes0:amd64 (1.14-3ubuntu3) ...
Setting up libglvnd0:amd64 (1.4.0-1) ...
Setting up libxcb-glx0:amd64 (1.14-3ubuntu3) ...
Setting up libedit2:amd64 (3.1-20210910-1build1) ...
Setting up libsensors-config (1:3.6.0-7ubuntu1) ...
Setting up xkb-data (2.33-1) ...
Setting up libxcb-shm0:amd64 (1.14-3ubuntu3) ...
Setting up libopengl0:amd64 (1.4.0-1) ...
Setting up libxxf86vm1:amd64 (1:1.1.4-1build3) ...
Setting up libxcb-present0:amd64 (1.14-3ubuntu3) ...
Setting up libxfixes3:amd64 (1:6.0.0-1) ...
Setting up libxcb-sync1:amd64 (1.14-3ubuntu3) ...
Setting up xz-utils (5.2.5-2ubuntu1) ...
update-alternatives: using /usr/bin/xz to provide /usr/bin/lzma (lzma) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/lzma.1.gz because associated file /usr/share/man/man1/xz.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/unlzma.1.gz because associated file /usr/share/man/man1/unxz.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzcat.1.gz because associated file /usr/share/man/man1/xzcat.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzmore.1.gz because associated file /usr/share/man/man1/xzmore.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzless.1.gz because associated file /usr/share/man/man1/xzless.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzdiff.1.gz because associated file /usr/share/man/man1/xzdiff.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzcmp.1.gz because associated file /usr/share/man/man1/xzcmp.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzgrep.1.gz because associated file /usr/share/man/man1/xzgrep.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzegrep.1.gz because associated file /usr/share/man/man1/xzegrep.1.gz (of link group lzma) doesn't exist
update-alternatives: warning: skip creation of /usr/share/man/man1/lzfgrep.1.gz because associated file /usr/share/man/man1/xzfgrep.1.gz (of link group lzma) doesn't exist
Setting up libllvm13:amd64 (1:13.0.1-2ubuntu2.1) ...
Setting up libsensors5:amd64 (1:3.6.0-7ubuntu1) ...
Setting up libglapi-mesa:amd64 (22.0.5-0ubuntu0.1) ...
Setting up libvulkan1:amd64 (1.3.204.1-2) ...
Setting up libxcb-dri2-0:amd64 (1.14-3ubuntu3) ...
Setting up libxshmfence1:amd64 (1.3-1build4) ...
Setting up libdrm-common (2.4.110-1ubuntu1) ...
Setting up libelf1:amd64 (0.186-1build1) ...
Setting up libxkbcommon0:amd64 (1.4.0-1) ...
Setting up libwayland-client0:amd64 (1.20.0-1ubuntu0.1) ...
Setting up libdrm2:amd64 (2.4.110-1ubuntu1) ...
Setting up libdrm-amdgpu1:amd64 (2.4.110-1ubuntu1) ...
Setting up libdrm-nouveau2:amd64 (2.4.110-1ubuntu1) ...
Setting up libgbm1:amd64 (22.0.5-0ubuntu0.1) ...
Setting up libdrm-radeon1:amd64 (2.4.110-1ubuntu1) ...
Setting up libgl1-mesa-dri:amd64 (22.0.5-0ubuntu0.1) ...
Setting up libegl-mesa0:amd64 (22.0.5-0ubuntu0.1) ...
Setting up libegl1:amd64 (1.4.0-1) ...
Setting up libglx-mesa0:amd64 (22.0.5-0ubuntu0.1) ...
Setting up libglx0:amd64 (1.4.0-1) ...
Setting up libgl1:amd64 (1.4.0-1) ...
Setting up libgl1-mesa-glx:amd64 (22.0.5-0ubuntu0.1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
**** Installing/updating calibre ****
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  133M  100  133M    0     0  28.6M      0  0:00:04  0:00:04 --:--:-- 34.6M
Failed to import PyQt module: PyQt6.QtWebEngineCore with error: libXtst.so.6: cannot open shared object file: No such file or directory
Creating symlinks...
	Symlinking /app/calibre/ebook-device to /usr/bin/ebook-device
	Symlinking /app/calibre/ebook-meta to /usr/bin/ebook-meta
	Symlinking /app/calibre/ebook-convert to /usr/bin/ebook-convert
	Symlinking /app/calibre/ebook-polish to /usr/bin/ebook-polish
	Symlinking /app/calibre/markdown-calibre to /usr/bin/markdown-calibre
	Symlinking /app/calibre/web2disk to /usr/bin/web2disk
	Symlinking /app/calibre/calibre-server to /usr/bin/calibre-server
	Symlinking /app/calibre/lrf2lrs to /usr/bin/lrf2lrs
	Symlinking /app/calibre/lrs2lrf to /usr/bin/lrs2lrf
	Symlinking /app/calibre/calibre-debug to /usr/bin/calibre-debug
	Symlinking /app/calibre/calibredb to /usr/bin/calibredb
	Symlinking /app/calibre/calibre-parallel to /usr/bin/calibre-parallel
	Symlinking /app/calibre/calibre-customize to /usr/bin/calibre-customize
	Symlinking /app/calibre/fetch-ebook-metadata to /usr/bin/fetch-ebook-metadata
	Symlinking /app/calibre/calibre-smtp to /usr/bin/calibre-smtp
	Symlinking /app/calibre/calibre to /usr/bin/calibre
	Symlinking /app/calibre/lrfviewer to /usr/bin/lrfviewer
	Symlinking /app/calibre/ebook-viewer to /usr/bin/ebook-viewer
	Symlinking /app/calibre/ebook-edit to /usr/bin/ebook-edit
Setting up command-line completion...
Installing zsh completion to: /usr/share/zsh/vendor-completions/_calibre
Failed to find directory to install bash completions, using default.
Installing bash completion to: /usr/share/bash-completion/completions/

____________________ WARNING ____________________
Setting up completion failed with error:
__________________________________________________


	Traceback (most recent call last):
	  File "calibre/linux.py", line 831, in setup_completion
	  File "calibre/linux.py", line 574, in write_completion
	  File "bypy-importer.py", line 279, in exec_module
	  File "calibre/gui2/viewer/main.py", line 15, in <module>
	  File "bypy-importer.py", line 279, in exec_module
	  File "calibre/gui2/viewer/ui.py", line 29, in <module>
	  File "bypy-importer.py", line 279, in exec_module
	  File "calibre/gui2/viewer/annotations.py", line 13, in <module>
	  File "bypy-importer.py", line 279, in exec_module
	  File "calibre/gui2/viewer/web_view.py", line 14, in <module>
	ImportError: cannot import name 'QWebEnginePage' from 'qt.webengine' (/app/calibre/lib/calibre-extensions/python-lib.bypy.frozen/qt/webengine.pyc)

Setting up desktop integration...

____________________ WARNING ____________________
Setting up desktop integration failed with error:
__________________________________________________


	Traceback (most recent call last):
	  File "calibre/linux.py", line 852, in setup_desktop_integration
	  File "calibre/linux.py", line 874, in do_setup_desktop_integration
	  File "calibre/linux.py", line 905, in install_xdg_junk
	  File "calibre/linux.py", line 890, in install_icons
	  File "calibre/linux.py", line 884, in install_single_icon
	  File "subprocess.py", line 364, in check_call
	  File "subprocess.py", line 345, in call
	  File "subprocess.py", line 966, in __init__
	  File "subprocess.py", line 1842, in _execute_child
	FileNotFoundError: [Errno 2] No such file or directory: 'xdg-icon-resource'

Creating un-installer: /usr/bin/calibre-uninstall


There were 2 warnings

* Setting up completion failed with error:

* Setting up desktop integration failed with error:

[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by aptalca** [comment]
those are harmless errors about bash completion and desktop integration, neither of which are used in this type of setup
