### ISSUE TITLE
F2B Discord Notification action failing 

### ISSUE THREAD

**Issue by xenolithis** [linuxserver/docker-mods#520]
hello,

I'm attempting to integrate the [f2bdiscord](https://github.com/linuxserver/docker-mods/tree/swag-f2bdiscord) and am seeing the below error when bans are triggered. `Fail2Ban.py returns 1`

fail2ban.log
```
2022-11-04 19:24:42,943 fail2ban.filter         [405]: INFO    [nginx-unauthorized] Found  <external-ipv4>  - 2022-11-04 19:24:42
2022-11-04 19:24:46,949 fail2ban.filter         [405]: INFO    [nginx-unauthorized] Found  <external-ipv4>  - 2022-11-04 19:24:46
2022-11-04 19:24:52,957 fail2ban.filter         [405]: INFO    [nginx-unauthorized] Found <external-ipv4>  - 2022-11-04 19:24:52
2022-11-04 19:24:58,966 fail2ban.filter         [405]: INFO    [nginx-unauthorized] Found <external-ipv4> - 2022-11-04 19:24:58
2022-11-04 19:25:04,174 fail2ban.filter         [405]: INFO    [nginx-unauthorized] Found  <external-ipv4>  - 2022-11-04 19:25:03
2022-11-04 19:25:04,366 fail2ban.actions        [405]: NOTICE  [nginx-unauthorized] Ban  <external-ipv4> 
2022-11-04 19:25:04,550 fail2ban.utils          [405]: ERROR   7f0db185d150 -- exec: python3 /config/fail2ban/Fail2Ban.py -a ban -j nginx-unauthorized -i  <external-ipv4> -t 12000 -f 5
2022-11-04 19:25:04,550 fail2ban.utils          [405]: ERROR   7f0db185d150 -- stderr: 'Traceback (most recent call last):'
2022-11-04 19:25:04,550 fail2ban.utils          [405]: ERROR   7f0db185d150 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 95, in <module>'
2022-11-04 19:25:04,550 fail2ban.utils          [405]: ERROR   7f0db185d150 -- stderr: '    data = Helpers(args.ip).data if "ban" in args.action else {}'
2022-11-04 19:25:04,550 fail2ban.utils          [405]: ERROR   7f0db185d150 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 64, in __init__'
2022-11-04 19:25:04,550 fail2ban.utils          [405]: ERROR   7f0db185d150 -- stderr: "    self.reader = geoip2.database.Reader('/config/geoip2db/GeoLite2-City.mmdb')"
2022-11-04 19:25:04,551 fail2ban.utils          [405]: ERROR   7f0db185d150 -- stderr: '  File "/usr/lib/python3.9/site-packages/geoip2/database.py", line 85, in __init__'
2022-11-04 19:25:04,551 fail2ban.utils          [405]: ERROR   7f0db185d150 -- stderr: '    self._db_reader = maxminddb.open_database(fileish, mode)'
2022-11-04 19:25:04,551 fail2ban.utils          [405]: ERROR   7f0db185d150 -- stderr: '  File "/usr/lib/python3.9/site-packages/maxminddb/__init__.py", line 69, in open_database'
2022-11-04 19:25:04,551 fail2ban.utils          [405]: ERROR   7f0db185d150 -- stderr: '    return Reader(database, mode)'
2022-11-04 19:25:04,551 fail2ban.utils          [405]: ERROR   7f0db185d150 -- stderr: '  File "/usr/lib/python3.9/site-packages/maxminddb/reader.py", line 57, in __init__'
2022-11-04 19:25:04,551 fail2ban.utils          [405]: ERROR   7f0db185d150 -- stderr: '    with open(database, "rb") as db_file:  # type: ignore'
2022-11-04 19:25:04,551 fail2ban.utils          [405]: ERROR   7f0db185d150 -- stderr: "FileNotFoundError: [Errno 2] No such file or directory: '/config/geoip2db/GeoLite2-City.mmdb'"
2022-11-04 19:25:04,551 fail2ban.utils          [405]: ERROR   7f0db185d150 -- returned 1
2022-11-04 19:25:04,551 fail2ban.actions        [405]: ERROR   Failed to execute ban jail 'nginx-unauthorized' action 'discordEmbed' info 'ActionInfo({'ip': ' <external-ipv4> ', 'family': 'inet4', 'fid': <function Actions.ActionInfo.<lambda> at 0x7f0db344fd30>, 'failures': 5, 'bantime': 12000, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x7f0db344d430>})': Error banning  <external-ipv4> 
```

jail.local
```
## Version 2022/01/09 - Changelog: https://github.com/linuxserver/docker-swag/commits/master/root/defaults/jail.local
# This is the custom version of the jail.conf for fail2ban
# Feel free to modify this and add additional filters
# Then you can drop the new filter conf files into the fail2ban-filters
# folder and restart the container

[DEFAULT]
# Prevents banning LAN subnets
ignoreip = 10.0.0.0/8
           192.168.0.0/16
           172.16.0.0/12

# Changes the default ban action from "iptables-multiport", which causes issues on some platforms, to "iptables-allports".
banaction = iptables-allports 


# "bantime" is the number of seconds that a host is banned.
bantime  = 12000

# A host is banned if it has generated "maxretry" during the last "findtime"
# seconds.
findtime  = 600

# "maxretry" is the number of failures before a host get banned.
maxretry = 5


[ssh]
enabled = false

[nginx-http-auth]
enabled  = true
filter   = nginx-http-auth
port     = http,https
logpath  = /config/log/nginx/error.log
action  = discordEmbed[bantime=2]
	  iptables-allports[name=nginx-http-auth]]          
[nginx-badbots]
enabled  = true
port     = http,https
filter   = nginx-badbots
logpath  = /config/log/nginx/access.log
maxretry = 2
action  = discordEmbed[bantime=2]
	  iptables-allports[name=nginx-badbots]
[nginx-botsearch]
enabled  = true
port     = http,https
filter   = nginx-botsearch
logpath  = /config/log/nginx/access.log
action  = discordEmbed[bantime=2]
	  iptables-allports[name=nginx-botsearch]
[nginx-deny]
enabled  = true
port     = http,https
filter   = nginx-deny
logpath  = /config/log/nginx/error.log
action  = discordEmbed[bantime=2]
	  iptables-allports[name=nginx-deny]
[nginx-unauthorized]
enabled  = true
port     = http,https
filter   = nginx-unauthorized
logpath  = /config/log/nginx/unauthorized.log
action  = discordEmbed[bantime=2]
	  iptables-allports[name=nginx-unauthorized]
```

**Comment by xenolithis** [comment]
updated my filter & actions to use .local files but have not seen any changes

```
root@da6622169be4:/# cat /config/fail2ban/nginx-http-auth.local 
[nginx-http-auth]

filter  = nginx-http-auth
enabled = true
port    = http,https
logpath = /config/log/nginx/error.log
action  = discordEmbed[bantime=3]
          iptables-allports[name=nginx-http-auth]
root@da6622169be4:/# 
````

**Comment by memehammad** [comment]
Exact same issue here. Any way to fix this that doesnt require switching to crowdsec?
