### ISSUE TITLE
add hosts error

### ISSUE THREAD

**Issue by utlimate** [linuxserver/docker-mods#703]
Adding new host '10.253.0.21' (10.253.0.21)
Traceback (most recent call last):
  File "/usr/local/bin/rffmpeg", line 954, in <module>
    run_control(config)
  File "/usr/local/bin/rffmpeg", line 942, in run_control
    return rffmpeg_click(obj={})
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/bin/rffmpeg", line 824, in rffmpeg_click_add
    cur.execute(
sqlite3.OperationalError: table hosts has no column named created

**Comment by aptalca** [comment]
@junkman690 fyi
