### ISSUE TITLE
[BUG] Setting up desktop integration failed

### ISSUE THREAD

**Issue by oywino** [linuxserver/docker-mods#979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Name of mod

  DOCKER_MODS=linuxserver/mods:universal-calibre

### Name of base container

    image: lscr.io/linuxserver/calibre-web:0.6.23

### Current Behavior

```
calibre-web  | Setting up desktop integration...
calibre-web  | 
calibre-web  | ____________________ WARNING ____________________
calibre-web  | Setting up desktop integration failed with error:
calibre-web  | __________________________________________________
calibre-web  | 
calibre-web  | 
calibre-web  |  Traceback (most recent call last):
calibre-web  |    File "calibre/linux.py", line 859, in setup_desktop_integration
calibre-web  |    File "calibre/linux.py", line 881, in do_setup_desktop_integration
calibre-web  |    File "calibre/linux.py", line 961, in install_xdg_junk
calibre-web  |    File "subprocess.py", line 413, in check_call
calibre-web  |  subprocess.CalledProcessError: Command 'xdg-desktop-menu install --noupdate ./calibre-gui.desktop' returned non-zero exit status 3.
calibre-web  | 
calibre-web  | Creating un-installer: /usr/bin/calibre-uninstall
calibre-web  | 
calibre-web  | 
calibre-web  | There were 2 warnings
calibre-web  | 
calibre-web  | * Setting up completion failed with error:
calibre-web  | 
calibre-web  | * Setting up desktop integration failed with error:
calibre-web  | 
calibre-web  | [custom-init] No custom files found, skipping...
calibre-web  | [ls.io-init] done.

```

### Expected Behavior

Not sure.

### Steps To Reproduce

1. run docker compose YAML
2. Check the log
3. launch calibre-web

### Environment

```markdown
- OS: QNAP NAS Container Station Service
- How docker service was installed:

version: '3'

services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.23
    container_name: calibre-web

    environment:
      PUID: 1000
      PGID: 1000
      LANG: nb_NO.UTF-8
      TZ: Europe/Oslo
      DOCKER_MODS: linuxserver/mods:universal-calibre

    volumes:
      - /share/Public/calibre/data:/config
      - /share/Public/calibre/library:/books
    ports:
      - 8083:8083
```

### CPU architecture

x86-64

### Docker creation

```bash
version: '3'

services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.23
    container_name: calibre-web

    environment:
      PUID: 1000
      PGID: 1000
      LANG: nb_NO.UTF-8
      TZ: Europe/Oslo

    volumes:
      - /share/Public/calibre/data:/config
      - /share/Public/calibre/library:/books
    ports:
      - 8083:8083
```

### Container logs

```bash
[2024-11-18 04:00:01,467]  WARN {apscheduler.executors.default:120} Run time of job "delete temp (trigger: cron[hour='4'], next run at: 2024-11-19 04:00:00 CET)" was missed by 0:00:01.467148
[2024-11-18 04:10:00,001]  INFO {apscheduler.executors.default:123} Running job "end scheduled task (trigger: cron[hour='4', minute='10'], next run at: 2024-11-19 04:10:00 CET)" (scheduled at 2024-11-18 04:10:00+01:00)
[2024-11-18 04:10:00,002]  INFO {apscheduler.executors.default:144} Job "end scheduled task (trigger: cron[hour='4', minute='10'], next run at: 2024-11-19 04:10:00 CET)" executed successfully
[2024-11-18 14:43:49,559]  INFO {cps.server:319} webserver stop (restart=False)
[2024-11-18 14:43:49,560]  INFO {apscheduler.scheduler:212} Scheduler has been shut down
[2024-11-18 14:43:49,608]  INFO {cps.server:298} Performing shutdown of Calibre-Web
[2024-11-18 14:46:40,207]  WARN {cps.config_sql:384} Log path  not valid, falling back to default
[2024-11-18 14:46:40,914]  INFO {cps:175} Starting Calibre Web...
[2024-11-18 14:46:43,226]  WARN {py.warnings:109} /lsiopy/lib/python3.10/site-packages/flask_limiter/extension.py:333: UserWarning: Using the in-memory storage for tracking rate limits as no storage was explicitly specified. This is not recommended for production use. See: https://flask-limiter.readthedocs.io#configuring-a-storage-backend for documentation about configuring the storage backend.
  warnings.warn(

[2024-11-18 14:46:44,780]  INFO {apscheduler.scheduler:181} Scheduler started
[2024-11-18 14:46:44,782]  INFO {apscheduler.scheduler:895} Added job "delete temp" to job store "default"
[2024-11-18 14:46:44,783]  INFO {apscheduler.scheduler:895} Added job "end scheduled task" to job store "default"
[2024-11-18 14:46:44,784]  INFO {apscheduler.scheduler:895} Added job "immediately delete temp" to job store "default"
[2024-11-18 14:46:44,786]  INFO {apscheduler.executors.default:123} Running job "immediately delete temp (trigger: date[2024-11-18 14:46:44 CET], next run at: 2024-11-18 14:46:44 CET)" (scheduled at 2024-11-18 14:46:44.784033+01:00)
[2024-11-18 14:46:44,818]  INFO {apscheduler.scheduler:641} Removed job 9dc1d48693ea479cab7faa7c6db1a870
[2024-11-18 14:46:44,825]  INFO {apscheduler.executors.default:144} Job "immediately delete temp (trigger: date[2024-11-18 14:46:44 CET], next run at: 2024-11-18 14:46:44 CET)" executed successfully
[2024-11-18 14:46:47,488]  WARN {py.warnings:109} /lsiopy/lib/python3.10/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from this module in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4

[2024-11-18 14:46:51,783]  INFO {cps.server:218} Starting Gevent server on [::]:8083
```

**Comment by aptalca** [comment]
https://github.com/linuxserver/docker-mods/pull/980/files

**Comment by oywino** [comment]
> https://github.com/linuxserver/docker-mods/pull/980/files

Well, if they're harmless and ignorable, then please tell me how to do a PDF 2 EPUB conversion from the Calibre-Web UI cause I cannot figure it out.

**Comment by aptalca** [comment]
No idea. I don't see anything about it in the logs you posted.

**Comment by oywino** [comment]
Well, I came here because I do not have any issues with Calibre-web as such. My questions are purely related to the conversion mod add-in or plug-in or whatever it is.

**Comment by j0nnymoe** [comment]
In terms of the setup, you need to make sure the binary is set correctly within calibre-web (Calibre-Web -> Admin -> Basic Configuration -> External binaries) 
, then once that is set I believe the option becomes available.

**Comment by aptalca** [comment]
> Well, I came here because I do not have any issues with Calibre-web as such. My questions are purely related to the conversion mod add-in or plug-in or whatever it is.

All this mod does is add the calibre binary in. That's all. It doesn't add or modify any feature or function other than that.

Calibre-web manages all the conversions through the calibre binary. If there is an issue with that, that's calibre-web's territory.

**Comment by oywino** [comment]
Wow, great! I managed to get the "plug-in" working. At least it appears so. When I select; "From PDF to EPUB" and click on the convert button, I get a message at the bottom of the web page saying "Book successfully queued for converting to EPUB"
This message disappears after 3 seconds, but so what? Where do I find the epub file?
![image](https://github.com/user-attachments/assets/e32b4c6d-6440-4cc9-bf74-dd29802bde94)

**Comment by aptalca** [comment]
Those are all questions for calibre-web.

Closing
